### ISSUE TITLE
Image loading order and High RAM usage

### ISSUE THREAD

**Issue by GustJc** [Aeonss/WebtoonReader#1]
Very nice tool for reading webtoons locally but there are a few problems.

### First (Fix ordering)
I understand that it gets the images by the OS alphabetic sorting.
But it's very common that chapters are named as
1.jpg ... 9.jpg, 10.jpg, 11.jpg

As of right now (ver1.1). I've printed to order and WebtoonReader actually loads them like.
`1.jpg - 10.jpg - 11.jpg - 12.jpg - 13.jpg - 14.jpg - 15.jpg - 16.jpg - 17.jpg - 18.jpg - 19.jpg - 2.jpg - 20.jpg
`

I fixed this by trying to do a numeric reordering at the Fill function first. So the common cases where the pages are just numbers would be correctly ordered. You just need to import re at the beginning of the file and change the fill function.

    def fill(self):
        if os.path.exists(self.path):
            files = [f for f in os.listdir(self.path)]
            
            search = lambda x: re.search(r'\d+', x)
            if_search = lambda x: int(search(x).group()) if search(x) else float('inf')
            files_sorted = sorted(files, key=if_search)
            
            # Gets all images from directory and adds to list
            for name in files_sorted:

### Second (HUGE RAM USAGE)
This is by far the biggest problem.
This tool is too RAM intensive.

You might not have noticed if you only tried it with small chapters. I myself only noticed it when my PC started to shutdown after trying to open a webtoon folder with 300+ pages.

Loading a **100 pages 100 mb sized** webtoon is actually consuming **8.5 Gigs of RAM**

I'm not sure how Tkinker handles it canvas. But it might be necessary to dynamically load the pages to solve this issue.
I don't think there is an easy way out of this.

### Third (Invert mouse drag)
Just a suggestion. Maybe add a invert mouse drag options.

I actually prefer to scroll upwards to I changed it manually the yview to -deltaY

    def update_scroll(self, event):  
        deltaX = event.x - self._starting_drag_position[0]
        deltaY = event.y - self._starting_drag_position[1]
        self.canvas.xview('scroll', deltaX, 'units')
        self.canvas.yview('scroll', -deltaY, 'units')
        self._starting_drag_position =  (event.x, event.y)

#### Edit: PS
I also deactivated the load last chapters feature here. 
As it takes a while to load big chapters, the programs appears stuck before you can even select the chapter you actually want to read, so I personally don't like this feature. An option to disable this might be nice for someone who doesn't know how to change the code.

And maybe add a progress bar to show how far along the image processing is?
I put a print on the console for myself here just to know how far along it is.
For example. A 35mb, 95 pages compressed chapter takes about 20-30 seconds to load here.

**Comment by Aeonss** [comment]
Hello, thank you for the feedback and issues found.

In the latest release, I've fixed the image loading order, to "natural sorting", which is what you described above. I did this for chapter loading but apparently not for image loading. This issue has been fixed.

For the large RAM usage, I've made the chapters now load 5 images at a time, instead of all them at once, saving memory usage of python having to store in memory all the images. It'll now garbage collect previous images upon scrolling past them. I've not yet created the feature to scroll backward to load the previous 5 images, but that will be implemented soon. For now, this SHOULD work, and will also help with your edit of loading last chapters taking a long time. Since the program now only loads 5 images at a time, I did not add an option to not load previous chapters since this issue shouldn't exist now due to the image load cap. In the future I'll also probably add a setting for users to choose how many images they want to load at once, dependent on their PC hardware.

As for your final issue, I've added an option to the settings menu for inverted mouse drag. In addition to this, I've also added it where any settings changed in the menu will update without the need to reload the program.

Thank you for documentating found issues, let me know if there's any other problems that you come across.
